### ISSUE TITLE
Microsoft logo and controls not rendered within map

### ISSUE THREAD

**Issue by j-wil** [rickyruiz/vue-azure-maps#10]
@rickyruiz Love the project keep up the good work. You should make some issues and label them help wanted so others can start to plugin.

I'm getting a weird issue where the Microsoft logo and anything else I add to the map renders outside of the top right corner. I'm not entirely sure if it is something I'm doing or not but any help would be appreciated.

![screenshot-d2fc8b0f ngrok io-2019 11 24-15-57-58 (1)](https://user-images.githubusercontent.com/7523651/69502318-8a55f980-0ed3-11ea-900d-2e1dcac3d8d5.png)

Here is the same issue in a stripped down codesandbox https://codesandbox.io/s/vue-azure-map-render-error-ys4vt

**Comment by rickyruiz** [comment]
This is most likely a CSS issue, the problem seems to be that you are using the following css rule set in the `<AzureMap />` component:

```
.azure-map {
  width: 100%;
  height: 100%:
}
```

If the height of the parent element wrapping the `<AzureMap/>` component is not defined, the `height: 100%` declaration block will evaluate to 0px.

<img width="1049" alt="Screen Shot 2019-11-24 at 8 00 53 PM" src="https://user-images.githubusercontent.com/12017329/69510126-c2236800-0ef8-11ea-927e-94f84698538d.png">

You do not necessarily need to have a fixed height, but I'd need to see your layout in order to help you fix it, could you share a reproducible example of your current modal layout.

Here's the [revised codesandbox](https://codesandbox.io/s/vue-azure-map-render-error-hxrk3).

**Comment by j-wil** [comment]
Gotcha that seemed to do the trick thanks for the insight.
